#cau hinh ket noi den postgresql
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/authdb
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update